#!/bin/sh

# Auto start
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
feh --bg-fill $HOME/Pictures/Fonds/night.png &
wmname LG3D &

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_side

# Escritorios
bspc monitor -d I II III IV V VI VII VIII IX X

# Look & feel
bspc config border_width         2
bspc config window_gap           6
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Colores de borde (Terminar de ajustar)
bspc config normal_border_color "#2E2F38"
bspc config focused_border_color "#8F3EFF"
bspc config active_border_color "#E3E8F5"
bspc config presel_feedback_color "#0E0F1A"

# Reglas de ventanas
bspc rule -a Gimp 		desktop='^8' state=floating follow=on
bspc rule -a Brave-browser 	desktop='^2'
bspc rule -a obsidian desktop='^3'
bspc rule -a mpv 		state=floating
bspc rule -a Kupfer.py 		focus=on
bspc rule -a Screenkey 		manage=off
bspc rule -a Pavucontrol 	state=floating
bspc rule -a blueman-manager	state=floating
bspc rule -a Lxappearamce	state=floating
bspc rule -a Rofi		state=floating manage=off
bspc rule -a burp-StartBurp	state=floating

sleep 1
~/.config/polybar/launch.sh &
