#################################
# Picom config para bspwm       #
#################################

# --- Opacidad general ---
active-opacity = 0.95;
inactive-opacity = 0.85;
frame-opacity = 0.80;

# --- Backend ---
backend = "glx";
vsync = true;
use-damage = true;

# --- Reglas de Opacidad específicas ---
opacity-rule = [
  "50:class_g = 'Bspwm' && class_i = 'presel_feedback'",
  "80:class_g = 'Rofi'",
  "80:class_g = 'Caja'",
  "99:class_g = 'Brave-browser'",
  "99:class_g = 'burp-StartBurp'",
  "100:class_g = 'Polybar'"            # Polybar SIEMPRE opaca
];

# --- Blur ---
blur-method = "dual_kawase";
blur-strength = 7;
blur-background = true;
blur-background-frame = true;
blur-background-fixed = true;

# --- Sombras ---
shadow = true;
shadow-radius = 12;
shadow-opacity = 0.4;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-exclude = [
  "class_g = 'Polybar'",
  "class_g = 'Rofi'",
  "class_g = 'Notification'"
];

# No aplicar blur ni transparencias a la barra
blur-background-exclude = [
  "class_g = 'Polybar'",
  "class_i = 'polybar'",
  "window_type = 'dock'"
];

# --- Exclusiones de transparencia ---
focus-exclude = [
  "class_g = 'Rofi'",
  "class_g = 'Polybar'"
];

# Evita sombras/blur en ventanas tipo dock (Polybar lo es)
wintypes = {
  dock = { shadow = false; blur-background = false; opacity = 1.0; };
};

